all:
  propel:
    class:        sfPropelDatabase
    param:
      phptype:    mysql
      host:       localhost

      # NOTE: if you change this name update also:
      #   * config/propel.ini
      #   * scripts/initdb.sh
      #   * scripts/abilis2asterisk/abilis2asterisk.php
      #
      database:   asterisell3_dev
      username:   asterisell3
      password:   TwdTttFGAmZXW92L
      encoding:   utf8
